# Generated by Django 5.2.14 on 2026-05-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='room_number',
            field=models.CharField(default='unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='student_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
